#!/bin/bash
#
# MAGENTO PHP IMAGE BUILD
#
# PHP-FPM on ALPINE
#
source envvars

PHP_PORTS=$BUILD_PHP_FPM_PORT

if [ $PHP_INSTALL_EXTENTSION_XDEBUG = $TRUE_KEY ];
then
    # Expose xdebug port if enabled
    PHP_PORTS="$PHP_PORTS $BUILD_PHP_XDEBUG_PORT"
fi

 # Building dockerfile
sed \
    -e "s;{PHP_VERSION};$BUILD_PHP_VERSION;g" \
    -e "s;{PHP_PORTS};$PHP_PORTS;g" \
    $BUILD_TEMPLATE > $BUILD_DESTINATION
	